# Generated by Django 2.0 on 2017-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_logo',
            field=models.CharField(default='https://www.w3schools.com/images/w3schools_green.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
